### ISSUE TITLE
Unit tests needed for CI/CD via Adobe Cloud Manager

### ISSUE THREAD

**Issue by jhuangsoftware** [adobe/aem-cif-project-archetype#23]
Hello,

I am using Adobe Cloud Manager as part of my CI/CD process to push changes to my STAGE and PROD environment.

I tried pushing latest release of the Venia Demo Store Project, 578dcdcb1d09bd4e3c526be98801eaaef6bde889, via Cloud Manager.

The code passed all code quality checked except "code coverage", which means the project must have unit tests to cover at least 50% of the core code/functions.

Can unit tests be added to the next release?

Thanks,

**Comment by mhaack** [comment]
The https://github.com/adobe/aem-core-cif-components are already covered by unit tests and we keep improving these. The current coverage report can be found here: https://codecov.io/gh/adobe/aem-core-cif-components

For the sample project we currently don't plan that, bit feel free to provide some.
