### ISSUE TITLE
Fix Layout Mode for  Category pages

### ISSUE THREAD

**Issue by duselton** [adobe/aem-cif-project-archetype#38]
**### Expected Behaviour**
When you change layout perspectives (desktop, tablet, iphone) that the page still has content

**### Actual Behaviour**
When you change the layout perspective, the query for content to Magento is lost and page goes blank.

#### Steps to Reproduce

view a category page which has products in preview mode, switch to layout mode and then change perspective. Poof, products are disappear.

**_View of category page in desktop mode after arriving in preview mode_**

![Screen Shot 2019-09-03 at 7 32 49 AM](https://user-images.githubusercontent.com/13228924/64182461-1f89aa80-ce1d-11e9-871f-7486439ffd1f.png)

**_Click on tablet or mobile to change perspective and products disappear_**

![Screen Shot 2019-09-03 at 7 33 12 AM](https://user-images.githubusercontent.com/13228924/64182487-257f8b80-ce1d-11e9-9ae3-a06d7c2eaa9f.png)

 

#### Logs taken while reproducing problem

**Comment by mhaack** [comment]
I can reproduce this and this is unfortunately working as designed. The editor reloads the page if one changes the layout preview, that makes removes the current category from the URL (see browser URL before / after). Without the category present in the URL the product list does not render anything, adding it back will fix it.

We work on making the product list more robust in editing mode.

**Comment by duselton** [comment]
Seems to work for the product page template/pages. But then again, not sure even see a grid under it. I will go add a few components to the catalog template policy and see if there even is a grid.

**Comment by duselton** [comment]
Ok, yes there is a grid underneath but the pages with products lists are not respecting the fact that there should be editiable areas of the page.  In authoring environment, go to a category with products in it and there are no editable area. There is an inherit area, but if you put something on a blank page upstream, like the catalog page, it is not inherited on a category page.

**Comment by mhaack** [comment]
The current category page templates have a grid (https://github.com/adobe/aem-cif-project-archetype/blob/master/src/main/archetype/samplecontent/src/main/content/jcr_root/content/__contentFolderName__/us/en/products/category-page/.content.xml#L19) but the product list component is not part of that, it is next to it. That is intentionally since it is "not made for authors", the component itself is hidden. If authors remove it from page they can not add it back.

This was a decision we made, but can be changed. WDYT should PDP & category templates be fully author-able?

**Comment by duselton** [comment]
Yes I do think Category and Product Pages should be fully authorable.  I believe that people will want to move things around and I believe that Target is big on talking about testing layouts etc. They should also allow for insertion of additional UI blocks as things like payment methods and source based inventory etc are needed to find space on the page in a way that flow with the product content. HTH
