### ISSUE TITLE
Template editor not working on clean AEM (6.4.5.0)

### ISSUE THREAD

**Issue by Jdruwe** [adobe/aem-cif-project-archetype#60]
### Expected Behaviour
Template editor should continue working after building with the 'autoInstallPackage' and 'autoInstallBundle' profiles selected.

### Actual Behaviour
The template editor is NOT working, console errors are thrown
<img width="1675" alt="Screenshot 2019-12-06 at 08 01 39" src="https://user-images.githubusercontent.com/4804496/70302956-aa07ee80-17fe-11ea-8b4e-fd6d38147a9a.png">

Video showing the issue: https://www.youtube.com/watch?v=XmB_xNg3dVo&feature=youtu.be

### Reproduce Scenario (including but not limited to)
- Spin up a clean AEM 6.4 instance 
- Upgrade to 6.4.5.0
- Build the archetype project using the  'autoInstallPackage' and 'autoInstallBundle' profiles
- Template editor shouldn't be working anymore

#### Platform and Version
- AEM: 6.4.5.0
- Archetype: 0.6.0

**Comment by mhaack** [comment]
Thanks @Jdruwe for reporting this, I can reproduce it, with AEM 6.5 GA as well.

**Comment by mhaack** [comment]
The issue was fixed with https://github.com/adobe/commerce-cif-connector/pull/76 and we will release a new connector version very soon.
