### ISSUE TITLE
Template Editor is broken in version 0.6.0 & 0.6.2

### ISSUE THREAD

**Issue by wesleyzhang2709** [adobe/aem-cif-project-archetype#70]
### Expected Behaviour
![image](https://user-images.githubusercontent.com/52417800/72675827-054b2300-3ac5-11ea-96ac-7b6d0ffc08b3.png)

### Actual Behaviour
![image](https://user-images.githubusercontent.com/52417800/72675802-8fdf5280-3ac4-11ea-8b63-1a3705cc1ea3.png)

#### Steps to Reproduce
Use version 0.6.2 & 0.6.0 to create a new cif project and enable DoptionEmbedConnector
mvn archetype:generate ^
 -DarchetypeGroupId=com.adobe.commerce.cif ^
 -DarchetypeArtifactId=cif-project-archetype ^
 -DoptionEmbedConnector=y ^
 -DarchetypeVersion=0.6.2

#### Platform and Version
CIF archetype: 0.6.0 & 0.6.2
#### Sample Code that illustrates the problem

How to fix. 
Please release a new archetype and change cif connect version to 0.7.1. 
https://github.com/adobe/aem-cif-project-archetype/blob/master/src/main/archetype/pom.xml
![image](https://user-images.githubusercontent.com/52417800/72675873-bd78cb80-3ac5-11ea-87ef-271234e0b6cc.png)

**Comment by herzog31** [comment]
This issue is fixed with release 0.7.0: https://github.com/adobe/aem-cif-project-archetype/releases/tag/cif-project-archetype-0.7.0.
