### ISSUE TITLE
cssId variable in generated clientlib-base .content.xml

### ISSUE THREAD

**Issue by godanny86** [adobe/aem-cif-project-archetype#72]
### Expected Behaviour
When generating a new project using the archetype all maven variables are replaced.

### Actual Behaviour

`${cssId}.grid` is leftover in the clientlib-base clientlib definition: 

https://github.com/adobe/aem-cif-project-archetype/blob/master/src/main/archetype/ui.apps/src/main/content/jcr_root/apps/__appsFolderName__/clientlibs/clientlib-base/.content.xml#L6

### Reproduce Scenario (including but not limited to)
Generate a new project using the archetype

**Comment by mhaack** [comment]
@godanny86 thanks, fixed with #72 and will already be included in today's release :-)
