### ISSUE TITLE
Commerce does not work for a new project based on Archetype 0.7.0 

### ISSUE THREAD

**Issue by aleksitto-gh** [adobe/aem-cif-project-archetype#78]
### Expected Behaviour
* A new project shall be ready to use when it is created by the provided archetype 0.7.0

### Actual Behaviour
* Created archetype contains errors

#### Steps to Reproduce
* Start a fresh AEM instance
* Create a new project using the latest archetype:
`mvn archetype:generate \
    -DarchetypeGroupId=com.adobe.commerce.cif \
    -DarchetypeArtifactId=cif-project-archetype \
    -DarchetypeVersion=0.7.0`
* Build and install project:
`mvn clean install -PautoInstallAll,adobe-public`
* Open package manager
* Find "core-cif-components-apps-0.7.0.zip" package
* Check its dependencies
* "day/cq60/product:cif-connector-content:0.8.0" is missing and highlighted in red
* Open AEM Commerce Products console (http://localhost:4502/aem/products.html/var/commerce/products)
* Click Create - there no Bind Products item

I tried to add missed library dependency and after that I found that "core-cif-components-apps-0.7.0" requires additional dependency "cif-virtual-catalog-content". After including all missed dependencies all packages were installed correctly and I found the Bind Products item in the AEM Commerce Products console. But now I have another error when I click the "Bind Products" which shows "Unable to compile class for JSP: An error occurred at line: 15 in the generated java file Only a type can be imported."

Exception:

> org.apache.sling.scripting.jsp.jasper.JasperException: Unable to compile class for JSP: 
> 
> An error occurred at line: 15 in the generated java file
> Only a type can be imported. com.adobe.cq.commerce.virtual.catalog.data.CatalogDataResourceProviderFactory resolves to a package
> 
> An error occurred at line: 16 in the generated java file
> Only a type can be imported. com.adobe.cq.commerce.virtual.catalog.data.CatalogDataResourceProviderManager resolves to a package
> 
> An error occurred at line: 29 in the jsp file: /libs/commerce/gui/components/admin/products/bindproducttreewizard/commerceproviderdatasource/commerceproviderdatasource.jsp
> CatalogDataResourceProviderFactory cannot be resolved to a type
> 26: <%@include file="/libs/foundation/global.jsp" %>
> 27: <%
> 28:     // Get data for datasource
> 29:     Map<String, CatalogDataResourceProviderFactory<?>> dataResourceProviderFactories =
> 30:             sling.getService(CatalogDataResourceProviderManager.class).getProviderFactories();
> 31: 
> 32:     // Build datasource
> 
> 
> An error occurred at line: 30 in the jsp file: /libs/commerce/gui/components/admin/products/bindproducttreewizard/commerceproviderdatasource/commerceproviderdatasource.jsp
> CatalogDataResourceProviderManager cannot be resolved to a type
> 27: <%
> 28:     // Get data for datasource
> 29:     Map<String, CatalogDataResourceProviderFactory<?>> dataResourceProviderFactories =
> 30:             sling.getService(CatalogDataResourceProviderManager.class).getProviderFactories();
> 31: 
> 32:     // Build datasource
> 33:     ArrayList<Resource> resourceList = new ArrayList<Resource>();
> 
> 	at org.apache.sling.scripting.jsp.jasper.compiler.DefaultErrorHandler.javacError(DefaultErrorHandler.java:93)
> 	at org.apache.sling.scripting.jsp.jasper.compiler.ErrorDispatcher.javacError(ErrorDispatcher.java:330)
> 	at org.apache.sling.scripting.jsp.jasper.compiler.JDTCompiler.generateClass(JDTCompiler.java:136)
> 	at org.apache.sling.scripting.jsp.jasper.compiler.Compiler.compile(Compiler.java:304)
> 	at org.apache.sling.scripting.jsp.jasper.compiler.Compiler.compile(Compiler.java:282)
> 	at org.apache.sling.scripting.jsp.jasper.compiler.Compiler.compile(Compiler.java:269)
> 	at org.apache.sling.scripting.jsp.jasper.JspCompilationContext.compile(JspCompilationContext.java:501)

#### Platform and Version
* AEM 6.5
* Archetype 0.7.0

#### Logs taken while reproducing problem

**Comment by mhaack** [comment]
Please create the project with `optionEmbedConnector=y` option this should help. Or get the CIF Connector all package from https://search.maven.org/search?q=g:com.adobe.commerce.cif%20AND%20a:cif-connector-all and install before deploying the sample project.

**Comment by aleksitto-gh** [comment]
It works, thanks for the quick response

**Comment by mhaack** [comment]
👍
