### ISSUE TITLE
Add new CSS rules / styles for search and product list filtering

### ISSUE THREAD

**Issue by kevin-mitchell** [adobe/aem-cif-project-archetype#91]
### User Story
As a user I'd like to be able to have some basic styling in places for searching and filtering functionality. 

### Description & Motivation
Working towards allowing for filtering of search and product listing (e.g. category) pages it ([see this issue here](https://github.com/adobe/aem-core-cif-components/issues/198)) would be convenient to have some simple styles in demo-projects that provide a reasonable looking left bar for attribute filters. 

### Deliverables
Some very simple styling for new components introduced in any PRs related to ([aem-core-cif-components issue #198](https://github.com/adobe/aem-core-cif-components/issues/198))

### Acceptance Criteria
Building the archetype and deploying the demo store should include basic styles for the search related enhancements (primarily filters and some slightly different modified structure for search and category / product list templates)

### Verification Steps
1. Deploy code changes required for search filtering functionality
2. build and deploy this archtype
3. verify CSS styles are available to provide basic styling for any filtering or search related features that have been added

**Comment by mhaack** [comment]
Fixed by #92
