### ISSUE TITLE
Cannot See Mini Cart on Venia Store on Top Right Corner

### ISSUE THREAD

**Issue by atif92** [adobe/aem-cif-project-archetype#93]
I am unable to see the mini cart on top right corner after creating a new project using demo-store.all-0.9.0.zip from latest release here https://github.com/adobe/aem-cif-project-archetype/releases and installing it through package manager in my AEM 6.5. Do I need to install it separately? I am following this integration through https://www.adobe.io/apis/experiencecloud/commerce-integration-framework/getting-started.html

**Comment by mhaack** [comment]
Hi @atif92 to get the shopping cart, checkout etc working you need one extra step. See https://www.adobe.io/apis/experiencecloud/commerce-integration-framework/tutorials.html#!AdobeDocs/commerce-cif-documentation/master/tutorials/03-shopping-cart-dispatcher.md

**Comment by mhaack** [comment]
Also, see https://github.com/adobe/aem-core-cif-components/tree/master/dispatcher

This preconfigured is primary for local development and must be adjusted for your production setup needs.

**Comment by atif92** [comment]
@mhaack I agree I would need Dispatcher Set Up to route my cart component to Magento, What I was referring to is why the UI itself isnt there, where as the link I shared that tutorials shows the UI of cart and button to add product to card is atleast there as soon as basic integration between AEM and Magento is done.

**Comment by mhaack** [comment]
The UI (mini cart icon, etc) will only be visible if you have Dispatcher installed and access the demo site via the dispatcher. The cart JS tries to load the shopping cart. These calls will fail without the dispatcher (you can see that in the browser console) and no mini cart icon is rendered.

Hence Dispatcher config is a must, for now, to get it working. (I see in the intro video AEM is accessed via localhost:4502, not sure how this was done, normally the mini cart should not be visible if AEM is accessed directly)

**Comment by atif92** [comment]
Thanks alot. That helped
